### ISSUE TITLE
first render

### ISSUE THREAD

**Issue by huizezhang-sherry** [numbats/monash-quarto-thesis#1]
In `01-chap1.qmd`, the `urca` package is needed to run the code chunk under Section *Results from analyses* (otherwise a NULL model). This also affects subsequent latex lines: `$\beta = r sprintf("%.2f", adbudget)$,` etc, which causes the render to fail when rendering the template for the first time. 

Maybe at least library the package or use a more straightforward example for templating?

**Comment by robjhyndman** [comment]
Fixed in https://github.com/numbats/monash-quarto-thesis/commit/1a79d752d7f48173bf659e24adca58d13469cab8
