### ISSUE TITLE
Issues changing citation style

### ISSUE THREAD

**Issue by pbousquets** [numbats/monash-quarto-thesis#2]
Hi! I really liked you template and I'm trying to use it. I needed to change the citation style, due to formal requirements. I downloaded the Vancouver style [here](https://github.com/citation-style-language/styles/tree/master) but I find this issue:
```
compilation failed- error
Undefined control sequence.
l.316 \CSLLeftMargin
                    {1. }%
```

The html render if fine, it's just something in the .tex file. 

Do you have any idea on what the problem is? Thanks!

**Comment by robjhyndman** [comment]
I've updated the template so that it should now work with any CSL style

**Comment by pbousquets** [comment]
Thanks a lot! Your repo has helped a lot to start writing my dissertation!
